<?
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["9"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["9"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["9"]="D";
$PERM["/"]["9"]="W";
$PERM["/"]["*"]="R";
$PERM["search"]["6"]="W";
$PERM["products"]["6"]="W";
$PERM["services"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["contacts"]["6"]="W";
$PERM["company"]["6"]="W";
$PERM["index.php"]["6"]="W";
?>