<?
$aMenuLinks = Array(
	Array(
		"Анонсы", 
		"/exam/partneram/raspisanie-meropriyatiy/index.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Архив", 
		"/exam/partneram/raspisanie-meropriyatiy/arkhiv.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"", 
		"/exam/partneram/raspisanie-meropriyatiy/arkhiv.php", 
		Array(), 
		Array(), 
		"" 
	)
);
?>